# Generated by Django 3.1.1 on 2020-09-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_icon', models.ImageField(upload_to='title_ico/')),
            ],
        ),
        migrations.CreateModel(
            name='slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.ImageField(blank=True, default='slides_img/default/default.png', upload_to='slides_img/')),
                ('slide_title', models.CharField(max_length=100)),
                ('slide_body_text', models.TextField()),
            ],
        ),
    ]
