# Generated by Django 3.1.1 on 2020-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_title',
            name='title_icon',
            field=models.ImageField(blank=True, default='title_ico/default/default.png', upload_to='title_ico/'),
        ),
    ]
