# Generated by Django 3.1.1 on 2020-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_auto_20200903_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='services/img/default/default.png', upload_to='services/img/')),
                ('title', models.CharField(max_length=191)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.AlterField(
            model_name='our_customers',
            name='img',
            field=models.ImageField(blank=True, default='services/img/default/default.png', upload_to='services/img/'),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='img',
            field=models.ImageField(blank=True, default='services/img/default/default.png', upload_to='services/img/'),
        ),
    ]
