# Generated by Django 3.1.1 on 2020-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_auto_20200903_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='img',
            field=models.ImageField(blank=True, default='our_team/img/default/default.png', upload_to='our_team/img/'),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
