# Generated by Django 3.1.1 on 2020-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_auto_20200904_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_customers',
            name='title',
        ),
        migrations.AddField(
            model_name='our_customers',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='our_customers',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='our_customers',
            name='img',
            field=models.ImageField(blank=True, default='customers/img/default/default.png', upload_to='customers/img/'),
        ),
    ]
