# Generated by Django 3.1.1 on 2020-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_auto_20200904_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=21)),
                ('color', models.CharField(max_length=6)),
                ('color_ba', models.CharField(max_length=6)),
            ],
        ),
    ]
