import os
from pathlib import Path
BASE_DIR=Path(__file__).resolve().parent.parent
SECRET_KEY='v+9%l@@6upn5j(a#w^sp+$y4-am252o6_!d(8ab4l_!fn!)ah&'
DEBUG=True
ALLOWED_HOSTS=['maxgendev.pythonanywhere.com','127.0.0.1']
INSTALLED_APPS=[
	'control_panel.apps.ControlPanelConfig',
	'users.apps.UsersConfig',
	'main.apps.MainConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
]
MIDDLEWARE=[
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF='web_01.urls'
TEMPLATES=[
	{
		'BACKEND':'django.template.backends.django.DjangoTemplates',
		'DIRS':[str(BASE_DIR).replace("\\","/")+'/templates/']
		,
		'APP_DIRS':True,
		'OPTIONS':{
			'context_processors':[
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]
WSGI_APPLICATION='web_01.wsgi.application'
DATABASES={
	'default':{
		'ENGINE':'django.db.backends.sqlite3',
		'NAME':BASE_DIR/'db.sqlite3',
	}
}
AUTH_PASSWORD_VALIDATORS=[
	{
		'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]
LANGUAGE_CODE='en-us'
TIME_ZONE='UTC'
USE_I18N=True
USE_L10N=True
USE_TZ=True
STATIC_URL='/static/'
MEDIA_URL='/media/'
MEDIA_ROOT=str(BASE_DIR).replace("\\","/")+'/media/'
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),)
